# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0015_auto_20170511_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Fornecedor'),
        ),
        migrations.AlterField(
            model_name='notaservico',
            name='valorDiaria',
            field=models.FloatField(verbose_name='valorDiaria'),
        ),
    ]
