# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0018_auto_20170511_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacompra',
            name='valorProdutos',
            field=models.IntegerField(default=0, max_length=10, verbose_name='valorProdutos'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Fornecedor'),
        ),
        migrations.AlterField(
            model_name='notacompra',
            name='qtProd',
            field=models.IntegerField(max_length=10, verbose_name='qtProd'),
        ),
    ]
